[project]
name = "val"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.129.0",
    "pandas>=3.0.1",
    "setuptools>=82.0.0",
    "uvicorn>=0.41.0",
    "yfinance>=1.2.0",
]
